# Generated by Django 5.2.10 on 2026-01-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_addressentreprise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressentreprise',
            name='entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='core.entreprise'),
            preserve_default=False,
        ),
    ]
