# Generated by Django 5.2.10 on 2026-01-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_addressentreprise_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contenu',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
