# Generated by Django 5.2.10 on 2026-01-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contenu_is_active_contenu_is_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenu',
            name='height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contenu',
            name='width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
