# Generated by Django 5.2.10 on 2026-01-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contenu_height_contenu_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
